# This is the configuration file for DCEPT (Domain Controller Enticing Password
# Tripwire). You must choose notification preferences before deploying DCEPT.


# Master_Node: The IP address or hostname of the master DCEPT server. In a
# multi-server DCEPT topology, multiple DCEPT nodes synchronize using a master
# node. This is useful in AD replication setups where domains controllers are
# on different networks or where taps are impractical. Setting the master_node
# value will configure this DCEPT server as slave to that master node.
#
# master_node: localhost

# Honeytoken_host: The hostname or IP address the honeytoken generation server
# (HTTP) should bind. Otherwise it will bind to all interfaces.
#
# honeytoken_host: 0.0.0.0

# Honeytoken_param_name: The name of the URL parameter that contains the
# endpoint hostname. This is sent to the generation server and associated with
# the unique honeytoken. Any changes to the paramater name must be applied to
# the agent prior to deployment.
#
# honeytoken_param_name: honey

# Honeytoken_param_name: The name of the URL where master DCEPT instance will 
# listen for POST requests from the slave nodes.
#
# honeytoken_uri: /honeyuri

# Honeytoken_port: The port the password generation server's HTTP daemon should
# listen on. The default port is 8080.
#
#honeytoken_port: 8080

# Interface: The name of the interface sniffing the Kerberos traffic from
# the domain controller
#
interface: ens18

# Domain: The fully qualified domain name (FQDN) being seeded on the endpoints.
# Ideally this would be your primary domain to look as inconspicuous as
# possible. The domain will be passed to agents requesting honeytokens from the
# generation server.
#
domain: LABO.LAN

# Realm: The Active Directory realm associated with the domain.
#
realm: LABO

# Honey_username: The username being seeded on the endpoints. This username
# should should be real. It is safe to use the real domain administrator
# username.
#
honey_username: user01

# Sqlite_path: Path to Sqlite3 db file where the credentials generated by DCEPT
# will be stored.
#
# sqlite_path: honeytoken3.db

# John_path: Path where John the Ripper executable is located.
#
john_path: /opt/dcept/john/run/john


# Uncomment the following lines to enable notifications via email.
#
#smtp_host: smtp.example.com
#smtp_port: 25
#subject: DCEPT

# Uncomment the following lines to enable notifications via remote syslog.
# Currently only UDP is supported
#
# syslog_host = localhost
# syslog_port = 514

# Uncomment the following lines to enable notifications via log file.
#
file_path: ./shared/alerts.log

# Configures the log level. Critical, Error, Warning, Info. Debug, NotSet
#
log_level: DEBUG

